[build]
target = "wasm32-rlbox.json"

[target.'cfg(target_arch = "x86_64------")']
rustflags = [
    "-C", "link-arg=-Wl,--export-all",
    "-C", "link-arg=-Wl,--no-entry",
    "-C", "link-arg=-Wl,--growable-table",
    "-C", "link-arg=-Wl,--stack-first",
    "-C", "link-arg=-Wl,-z,stack-size=1048576",
    "-C", "link-arg=-Wl,--import-memory",
    "-C", "link-arg=-Wl,--import-table",
    "-C", "link-arg=bogus",
]
