[build]
rustflags = ["-C", "linker=../../rlbox_wasm2c_sandbox/build/_deps/wasiclang-src/bin/clang", "-C", "link-args=-Wl,--export-all -Wl,--no-entry -Wl,--growable-table -Wl,--stack-first -Wl,-z,stack-size=1048576 -Wl,--import-memory -Wl,--import-table"]
